/* SPDX-License-Identifier: GPL-2.0-or-later */

#pragma once

#define VIAL_KEYBOARD_UID {0x5C, 0x2B, 0xB4, 0x2A, 0x60, 0xB3, 0x8B, 0x46}

#define VIAL_UNLOCK_COMBO_ROWS { 0, 9 }
#define VIAL_UNLOCK_COMBO_COLS { 1, 7 }

#define DYNAMIC_KEYMAP_LAYER_COUNT 7
#define VIAL_COMBO_ENTRIES 24
#define VIAL_TAP_DANCE_ENTRIES 4

#define PERMISSIVE_HOLD
#define ACHORDION_STREAK
#define CAPS_WORD_INVERT_ON_SHIFT
#define CAPS_WORD_IDLE_TIMEOUT 5000

#define NO_MUSIC_MODE